version: '3.7'

services:
  app:
    container_name: dubs
    image: node:16-alpine
    command: sh -c "yarn install & yarn run dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - dubs-network
    depends_on:
      - directus

  database:
    container_name: database
    image: postgis/postgis:13-master
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - dubs-network
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'

  directus:
    container_name: directus
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - uploads:/directus/uploads
    networks:
      - dubs-network
    depends_on:
      - database
    environment:
      KEY: '${DIRECTUS_KEY}'
      SECRET: '${DIRECTUS_SECRET}'

      DB_CLIENT: '${DB_CLIENT}'
      DB_HOST: '${DB_HOST}'
      DB_PORT: '${DB_PORT}'
      DB_DATABASE: '${DB_DATABASE}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${POSTGRES_PASSWORD}'

      ADMIN_EMAIL: '${ADMIN_EMAIL}'
      ADMIN_PASSWORD: '${ADMIN_PASSWORD}'

networks:
  dubs-network:
volumes:
  data:
  uploads:
