name: Dubs apiculture CI

on:
  push:
    branches: [main]

  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      SSH_HOST:
        required: true
      SSH_USERNAME:
        required: true
      SSH_PASSWORD:
        required: true

jobs:
  build:
    environment: Nestor - clients
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm run -r build

      - name: Copy source on host
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: ./
          target: ~/dubs/tmp

      - name: Replace and restart application
        uses: appleboy/ssh-action@master
        env:
          PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          envs: PAYLAOD_SECRET,SMTP_PASS,AUTH_SECRET
          script: |
            . .profile
            rm -rf ~/dubs/app
            mv ~/dubs/tmp ~/dubs/app
            cd ~/dubs/app
            pnpm run --filter ./frontend serve
            pnpm run --filter ./backend serve
